project:
  type: website

website:
  title: "Jessica Benun's Portfolio"
  description: "A collection of my work and projects."
  site-url: https://jessbenun.github.io
  navbar:
    left:
      - text: About Me
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd 
    right:
      - icon: github
        href: https://github.com/jessbenun
        aria-label: GitHub
  page-footer: "© 2026 Jessica Benun. All rights reserved."


format:
  html:
    css: styles.css
    toc: false



