project:
  type: website

website:
  title: "Jessica Benun's Portfolio"
  description: "A collection of my work and projects."
  site-url: https://jessbenun.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: jbenun_system_info.qmd
        text: Assignment 01 - System Information  
    right:
      - icon: github
        href: https://github.com/jessbenun
        aria-label: GitHub
  page-footer: "© 2026 Jessica Benun. All rights reserved."


format:
  html:
    theme:
      - simplex
      - brand
    css: styles.css
    toc: true



